#!/usr/bin/python3
# -*- coding: utf-8 -*-
#@date   : 2019/5/5
#@author : Rong Ya-feng

import turtle
'''
turtle.screensize(400,300)
turtle.penup()
turtle.goto(-310,243)
turtle.pendown()
turtle.color("#2F4F4F")
turtle.write('date  :',False,align = "left",font = ("宋体",16,"normal"))
turtle.penup()
turtle.goto(-225,243)
turtle.pendown()
turtle.write('2019/5/5',False,align = "left",font = ("宋体",16,"normal"))
turtle.penup()
turtle.goto(-310,220)
turtle.pendown()
turtle.write('author:',False,align = "left",font = ("宋体",16,"normal"))
turtle.penup()
turtle.goto(-225,220)
turtle.pendown()
turtle.write('@肜肜的啊',False,align = "left",font = ("宋体",16,"normal"))
'''
turtle.pensize(2)
turtle.penup()
turtle.goto(90,90)
turtle.pendown()
turtle.setheading(90)

turtle.color('yellow')
turtle.begin_fill()
turtle.circle(120)
turtle.end_fill()
turtle.color('white')
turtle.begin_fill()
turtle.circle(90)
turtle.end_fill()

turtle.penup()
turtle.goto(52,34)
turtle.pendown()
turtle.setheading(0)
turtle.color("#FFD700")
turtle.begin_fill()
turtle.setheading(30)
for i in range(5):
    turtle.left(72)
    turtle.forward(18)
    turtle.right(144)
    turtle.forward(18)
turtle.end_fill()

turtle.penup()
turtle.goto(30,-60)
turtle.pendown()
turtle.color("#828282")
turtle.write('长在月亮边的星',False,align = "left",font = ("楷体",20,"normal"))
turtle.penup()
turtle.goto(60,-90)
turtle.pendown()
turtle.write('孤单仍放肆不停',False,align = "left",font = ("楷体",20,"normal"))
turtle.penup()
turtle.goto(120,-120)
turtle.pendown()
turtle.write('——太一《早恋》',False,align = "left",font = ("楷体",16,"normal"))
turtle.hideturtle()

turtle.done()