#!/usr/bin/python3
# -*- coding utf-8 -*-
# @author:Rong-Yafeng
# @date:2019/7/17

import turtle
import time

turtle.pensize(4)
turtle.hideturtle()
turtle.setup(1000, 600)
turtle.speed(10)
turtle.screensize(bg='#551A8B')
time.sleep(10)

# 画鼻子
turtle.penup()
turtle.seth(90)
turtle.fd(100)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor('#000000')
turtle.seth(45)
turtle.fd(25)
turtle.seth(135)
turtle.circle(25, 95)
turtle.seth(315)
turtle.fd(25)
turtle.end_fill()

# 画眼睛
turtle.penup()
turtle.seth(160)
turtle.fd(250)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor('#000000')
turtle.circle(50)
turtle.end_fill()
turtle.penup()
turtle.circle(50, 60)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor('#EE9A00')
turtle.circle(20)
turtle.end_fill()

turtle.penup()
turtle.seth(-9.5)
turtle.fd(530)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor('#000000')
turtle.circle(50)
turtle.end_fill()
turtle.penup()
turtle.circle(50, 230)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor('#EE9A00')
turtle.circle(20)
turtle.end_fill()

# 画脸
turtle.penup()
turtle.seth(195)
turtle.fd(600)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor('#551A8B')
turtle.circle(70)
turtle.end_fill()

turtle.begin_fill()
turtle.fillcolor('#EE9A00')
turtle.penup()
turtle.seth(240)
turtle.fd(99)
turtle.seth(285)
turtle.pendown()
turtle.circle(70, 180)
turtle.penup()
turtle.seth(225)
turtle.pendown()
turtle.circle(-140, 60)
turtle.end_fill()

turtle.penup()
turtle.seth(60)
turtle.fd(99)
turtle.seth(195)

turtle.seth(-11)
turtle.fd(720)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor('#EE9A00')
turtle.circle(70)
turtle.end_fill()

# 画嘴巴
turtle.penup()
turtle.seth(135)
turtle.fd(250)
turtle.pendown()
turtle.seth(-300)
turtle.circle(30, -65)
turtle.begin_fill()
turtle.fillcolor('#000000')
turtle.seth(165)
turtle.fd(140)
turtle.seth(195)
turtle.fd(140)
turtle.seth(-360)
turtle.circle(30, -65)
turtle.penup()
turtle.seth(-60)
turtle.circle(30, 65)
turtle.pendown()
turtle.seth(-70)
turtle.fd(240)
turtle.circle(55, 140)
turtle.seth(70)
turtle.fd(240)
turtle.end_fill()
turtle.seth(-110)
turtle.fd(80)
turtle.begin_fill()
turtle.fillcolor('#EE9A00')
turtle.seth(120)
turtle.circle(120, 123)
turtle.seth(-70)
turtle.fd(165)
turtle.circle(55, 140)
turtle.seth(72)
turtle.fd(165)
turtle.end_fill()

turtle.done()
